# Generated by Django 6.0.4 on 2026-04-24 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('program_course', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=20)),
                ('is_enrolled', models.BooleanField(default=True)),
                ('medical_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.eventschedule')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('schedule', 'department')},
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.athlete')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='tournaments.eventregistration')),
            ],
            options={
                'unique_together': {('registration', 'athlete')},
            },
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
